#!/usr/bin/env python3
"""Export our questions and our eval cases in the shapes jevcal expects.

jevcal (abhixhek/jevcal, MIT, see `docs/CREDITS.md`) is the missing
rigour under the confidence thresholds in airlock/policy.py, which were
picked by hand. It wants three files:

  questions.yaml     {model, questions: {id: {type, instructions, criteria, target}}}
  data.jsonl         {id, state, labels}
  predictions.jsonl  {id, model, answers, usage, latency_ms}

This script writes the first two from what we already have -- the live
question definitions in airlock/questions.py and the labelled cases in
eval/cases.jsonl -- so there is no second copy of either to drift.

`jevcal measure` produces the third itself. `--predictions` here is for the
case where you already have `eval/last_result.json` from `python3 -m
airlock.eval` and would rather not pay for the calls twice.

Only the two Jev-decided guards are exported. The rules-table cases are
decided in pure code, so there is no threshold to calibrate for them.
"""
import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from airlock import questions as q_mod
from airlock import scope as scope_mod
from airlock.eval import load_cases

OUT_DIR = REPO_ROOT / "eval" / "jevcal"

# The accuracy jevcal must hold among the decisions it keeps. 0.99 because a
# deny is visible to a person and a false one is expensive; everything below
# the threshold it picks falls back to allowing, which is the guard's whole
# failure posture anyway.
DEFAULT_TARGET = 0.99

GUARDS = {
    "tier_guard": "task_kind",
    "tool_choice_guard": "search_intent",
}

# Per guard: the file stem, and which question ids belong to it. jevcal sends
# EVERY question in a questions.yaml for EVERY row of its data, so the two
# guards get their own pair of files. Combining them would ask task_kind about
# a Bash command's state, which is not a question our guard ever asks and would
# calibrate a threshold against noise.
SETS = {
    "tier": {
        "guard": "tier_guard",
        "questions": ("task_kind", "states_prior_failed_attempts", "brief_is_self_contained"),
    },
    "search": {
        "guard": "tool_choice_guard",
        "questions": ("search_intent",),
    },
}


def _flatten_criteria(criteria):
    """jevcal's spec wants a string per option. Ours are {what, not_for,
    examples} objects, which is the shape jev-behavior-study measured as
    working, so they are flattened rather than replaced -- the wording jevcal
    lints is then the wording we actually send, not a simplified stand-in."""
    out = {}
    for name, entry in criteria.items():
        if isinstance(entry, str):
            out[name] = entry
            continue
        parts = [entry.get("what", "")]
        if entry.get("not_for"):
            parts.append("Not for: %s" % entry["not_for"])
        if entry.get("examples"):
            parts.append("Examples: %s" % "; ".join(str(e) for e in entry["examples"]))
        out[name] = " ".join(p for p in parts if p)
    return out


def _instructions_text(instructions):
    if isinstance(instructions, str):
        return instructions
    parts = [instructions.get("question", "")]
    if instructions.get("focus"):
        parts.append(instructions["focus"])
    return " ".join(p for p in parts if p)


def _yaml_scalar(text):
    """A block scalar, so nothing in the wording has to be escaped and the
    file stays readable. pyyaml is not a dependency of this repository, so
    this writes the YAML by hand."""
    body = "\n".join("      " + line for line in str(text).splitlines()) or "      "
    return "|-\n" + body


def all_questions():
    out = {}
    out.update(q_mod.tier_questions())
    out.update(q_mod.bash_questions())
    return out


def build_questions(model="jev-latest", target=DEFAULT_TARGET, only=None):
    out = {name: question for name, question in all_questions().items()
           if only is None or name in only}

    lines = [
        "# Generated by tuning/jevcal_export.py from airlock/questions.py.",
        "# Do not edit by hand: regenerate it, so the wording jevcal lints is",
        "# always the wording the guard actually sends.",
        "#",
        "# Pin `model` to a specific version once the thresholds are tuned, so the",
        "# numbers in the lock file keep meaning what they meant.",
        "model: %s" % model,
        "",
        "questions:",
    ]
    for name, question in out.items():
        lines.append("  %s:" % name)
        lines.append("    type: %s" % question["type"])
        lines.append("    instructions: %s" % _yaml_scalar(_instructions_text(question["instructions"])))
        lines.append("    criteria:")
        for option, text in _flatten_criteria(question["criteria"]).items():
            lines.append('      "%s": %s' % (option, _yaml_scalar(text).replace("\n      ", "\n        ")))
        lines.append("    target: %s" % target)
        lines.append("")
    return "\n".join(lines)


def build_data(cases, guard=None):
    """One jevcal row per Jev-decided eval case: {id, state, labels}.

    The state is built by the SAME functions the guard uses, so a calibration
    run sees exactly what a live judgement sees. Nothing is reconstructed by
    hand here.
    """
    rows = []
    for case in cases:
        case_guard = case.get("guard")
        if guard is not None and case_guard != guard:
            continue
        question_id = GUARDS.get(case_guard)
        if not question_id:
            continue
        expected = (case.get("expected") or {}).get(question_id)
        if not expected:
            continue
        payload = case.get("payload") or {}
        ti = payload.get("tool_input") or {}

        if case_guard == "tier_guard":
            state = q_mod.tier_state(
                ti.get("subagent_type") or "", ti.get("model") or "",
                ti.get("description") or "", ti.get("prompt") or "")
        else:
            command = str(ti.get("command") or "")
            cwd = payload.get("cwd") or ""
            scope_result = scope_mod.classify_command(command, cwd)
            state = q_mod.bash_state(
                command, str(ti.get("description") or ""), cwd,
                scope_result["scope"], scope_mod.root_has_graphify_graph(scope_result))

        rows.append({"id": case["id"], "state": state, "labels": {question_id: expected}})
    return rows


def build_predictions_from_eval(result_path):
    """Reuse eval/last_result.json instead of paying for the calls again.

    airlock.eval records the chosen label and its confidence but not the full
    probability distribution, so `jevcal compile --measure top_prob` is the
    measure to use with these. A fresh `jevcal measure` run gives it more to
    work with; this is the cheap path, not the better one.
    """
    data = json.loads(Path(result_path).read_text())
    out = []
    for row in data.get("results") or []:
        guard = row.get("guard")
        question_id = GUARDS.get(guard)
        if not question_id or "error" in row:
            continue
        out.append({
            "id": row["id"],
            "model": "jev-latest",
            "answers": {question_id: {
                "choice": row.get("predicted_label"),
                "confidence": row.get("confidence"),
            }},
            "latency_ms": row.get("latency_ms") or 0,
            "usage": {},
        })
    return out


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=str(OUT_DIR))
    parser.add_argument("--cases", default=None)
    parser.add_argument("--model", default="jev-latest")
    parser.add_argument("--target", type=float, default=DEFAULT_TARGET)
    parser.add_argument("--predictions", default=None,
                        help="also convert an eval/last_result.json into predictions.jsonl")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    cases = load_cases(args.cases)

    # One combined questions file, for `jevcal lint` over all our wording.
    (out_dir / "questions.yaml").write_text(build_questions(args.model, args.target))
    print("wrote %s (all questions, for lint)" % (out_dir / "questions.yaml"))

    # Per-guard pairs, for measure/compile.
    for stem, spec in SETS.items():
        q_path = out_dir / ("questions-%s.yaml" % stem)
        d_path = out_dir / ("data-%s.jsonl" % stem)
        q_path.write_text(build_questions(args.model, args.target, only=spec["questions"]))
        rows = build_data(cases, guard=spec["guard"])
        d_path.write_text("".join(json.dumps(r) + "\n" for r in rows))
        print("wrote %s and %s (%d rows)" % (q_path, d_path, len(rows)))

    if args.predictions:
        preds = build_predictions_from_eval(args.predictions)
        (out_dir / "predictions.jsonl").write_text(
            "".join(json.dumps(p) + "\n" for p in preds))
        print("wrote %s (%d rows, from %s)"
              % (out_dir / "predictions.jsonl", len(preds), args.predictions))
    return 0


if __name__ == "__main__":
    sys.exit(main())
